# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/data/7z035-lpc.xdc

# Block Designs: D:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/PCIe_SSD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD || ORIG_REF_NAME==PCIe_SSD} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_processing_system7_0_0/PCIe_SSD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_processing_system7_0_0 || ORIG_REF_NAME==PCIe_SSD_processing_system7_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_axi_interconnect_2_0/PCIe_SSD_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_axi_interconnect_2_0 || ORIG_REF_NAME==PCIe_SSD_axi_interconnect_2_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_xbar_0/PCIe_SSD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_xbar_0 || ORIG_REF_NAME==PCIe_SSD_xbar_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_xlconcat_0_0/PCIe_SSD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_xlconcat_0_0 || ORIG_REF_NAME==PCIe_SSD_xlconcat_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_axi_pcie_0_0/PCIe_SSD_axi_pcie_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_axi_pcie_0_0 || ORIG_REF_NAME==PCIe_SSD_axi_pcie_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_xlconstant_0_0/PCIe_SSD_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_xlconstant_0_0 || ORIG_REF_NAME==PCIe_SSD_xlconstant_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_axi_cdma_0_0/PCIe_SSD_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_axi_cdma_0_0 || ORIG_REF_NAME==PCIe_SSD_axi_cdma_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_proc_sys_reset_1_0/PCIe_SSD_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_proc_sys_reset_1_0 || ORIG_REF_NAME==PCIe_SSD_proc_sys_reset_1_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_axi_interconnect_0_0/PCIe_SSD_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_axi_interconnect_0_0 || ORIG_REF_NAME==PCIe_SSD_axi_interconnect_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_xbar_1/PCIe_SSD_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_xbar_1 || ORIG_REF_NAME==PCIe_SSD_xbar_1} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_axi_interconnect_1_0/PCIe_SSD_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_axi_interconnect_1_0 || ORIG_REF_NAME==PCIe_SSD_axi_interconnect_1_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_xbar_2/PCIe_SSD_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_xbar_2 || ORIG_REF_NAME==PCIe_SSD_xbar_2} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_proc_sys_reset_0_0/PCIe_SSD_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_proc_sys_reset_0_0 || ORIG_REF_NAME==PCIe_SSD_proc_sys_reset_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_util_ds_buf_0_0/PCIe_SSD_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_util_ds_buf_0_0 || ORIG_REF_NAME==PCIe_SSD_util_ds_buf_0_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_ds_0/PCIe_SSD_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_ds_0 || ORIG_REF_NAME==PCIe_SSD_auto_ds_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_pc_0/PCIe_SSD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_pc_0 || ORIG_REF_NAME==PCIe_SSD_auto_pc_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_pc_3/PCIe_SSD_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_pc_3 || ORIG_REF_NAME==PCIe_SSD_auto_pc_3} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_us_0/PCIe_SSD_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_us_0 || ORIG_REF_NAME==PCIe_SSD_auto_us_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_cc_0/PCIe_SSD_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_cc_0 || ORIG_REF_NAME==PCIe_SSD_auto_cc_0} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_ds_1/PCIe_SSD_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_ds_1 || ORIG_REF_NAME==PCIe_SSD_auto_ds_1} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_pc_1/PCIe_SSD_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_pc_1 || ORIG_REF_NAME==PCIe_SSD_auto_pc_1} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_ds_2/PCIe_SSD_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_ds_2 || ORIG_REF_NAME==PCIe_SSD_auto_ds_2} -quiet] -quiet

# IP: d:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/ip/PCIe_SSD_auto_pc_2/PCIe_SSD_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_SSD_auto_pc_2 || ORIG_REF_NAME==PCIe_SSD_auto_pc_2} -quiet] -quiet

# XDC: D:/project/FPGA/FPGA_Design/TCL_project/Prj/pz_7z035_pcie/user/Hardware/bd/PCIe_SSD/PCIe_SSD_ooc.xdc
